apiVersion: batch/v1
kind: Job
metadata:
  name: salesforce-deploy
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: salesforce-deployer
      restartPolicy: Never
      containers:
      - name: sf-cli
        image: salesforce/cli:latest
        command:
          - /bin/sh
          - -c
          - |
            echo "Authorizing org..."
            sf org login jwt \
              --client-id $SF_CLIENT_ID \
              --jwt-key-file /certs/server.key \
              --username $SF_USERNAME \
              --alias sepsandbox
            echo "Deploying metadata..."
            sf project deploy start --manifest salesforce/manifest/package.xml --target-org sepsandbox --test-level RunLocalTests
        volumeMounts:
          - name: salesforce-key
            mountPath: /certs
            readOnly: true
        envFrom:
          - configMapRef:
              name: salesforce-config
          - secretRef:
              name: salesforce-secret
      volumes:
        - name: salesforce-key
          secret:
            secretName: salesforce-key
