name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure docker auth
        run: gcloud auth configure-docker --quiet

      # Build & push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/salesforce-deployer:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Run Salesforce deploy using Docker image
      - name: Run Salesforce Deployment
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            gcr.io/${{ secrets.GCP_PROJECT }}/salesforce-deployer:${{ github.sha }} \
            project deploy start \
              --manifest /app/manifest/package.xml \
              --target-org ${{ secrets.SF_AUTH_URL }} \
              --test-level RunLocalTests \
              --json
