name: Salesforce Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials jpcluster \
            --zone us-central1-a \
            --project ${{ secrets.GCP_PROJECT }}

      - name: Delete old Salesforce Jobs
        run: |
          kubectl delete jobs -l app=salesforce-deploy --ignore-not-found=true -n default

      - name: Apply ConfigMap & Secret
        run: |
          kubectl apply -f kubernetes/base/configmap.yaml -n default
          kubectl apply -f kubernetes/base/secret-salesforce.yaml -n default

      - name: Create Salesforce Job
        run: |
          kubectl create -f kubernetes/base/job-deploy.yaml -n default

      - name: Wait for Salesforce Job
        run: |
          JOB_NAME=$(kubectl get jobs -l app=salesforce-deploy -n default -o jsonpath="{.items[0].metadata.name}")
          kubectl wait --for=condition=complete job/$JOB_NAME -n default --timeout=600s