name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker login
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & push Docker image
      - name: Build & Push Salesforce Deployer Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jayaprakashitc/salesforce-deployer:latest

      # 4️⃣ Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Get GKE credentials
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # 6️⃣ Apply ConfigMap & Secret in Kubernetes
      - name: Apply Kubernetes ConfigMap and Secret
        run: |
          kubectl apply -f kubernetes/base/configmap.yaml
          kubectl apply -f kubernetes/base/secret-salesforce.yaml

      # 7️⃣ Deploy Salesforce Job
      - name: Deploy Salesforce Job
        env:
          IMAGE_TAG: jayaprakashitc/salesforce-deployer:latest
        run: |
          echo "Deploying Salesforce Job..."
          envsubst '${IMAGE_TAG}' < kubernetes/base/job-deploy.yaml | kubectl apply -f -

      # 8️⃣ Wait for Job to complete
      - name: Wait for Salesforce Job completion
        run: |
          JOB_NAME=$(kubectl get jobs -n default -o jsonpath='{.items[-1:].metadata.name}')
          echo "Waiting for job $JOB_NAME to complete..."
          kubectl wait --for=condition=complete --timeout=600s job/$JOB_NAME -n default
