name: Deploy Salesforce via GKE

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Authenticate GCP using Service Account
      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Install gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: grand-forge-472709-a0

      # 4️⃣ Install GKE auth plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q

      # 5️⃣ Get GKE cluster credentials
      - name: Configure GKE
        run: |
          gcloud container clusters get-credentials jpcluster \
            --zone us-central1-a \
            --project grand-forge-472709-a0

      - name: Deploy Salesforce Job to GKE
        run: |
            # Apply ConfigMap and Secret
            kubectl apply -f kubernetes/base/configmap.yaml -n default
            kubectl apply -f kubernetes/base/secret-salesforce.yaml -n default

            # Create new Salesforce Deployment Job
            kubectl create -f kubernetes/base/job-deploy.yaml -n default

            # Get Job name dynamically
            JOB_NAME=$(kubectl get jobs -n default -l app=salesforce-deploy -o jsonpath='{.items[0].metadata.name}')

            echo "Waiting for Job $JOB_NAME to complete..."
            if ! kubectl wait --for=condition=complete job/$JOB_NAME -n default --timeout=600s; then
             echo "Job failed or timed out. Showing logs:"
             POD_NAME=$(kubectl get pods -n default -l job-name=$JOB_NAME -o jsonpath='{.items[0].metadata.name}')
             kubectl describe pod $POD_NAME -n default
             kubectl logs $POD_NAME -n default
             exit 1
            fi