name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & push Salesforce Deployer Docker image
      - name: Build & Push Salesforce Deployer Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jayaprakashitc/salesforce-deployer:latest

      # 4️⃣ Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Get GKE cluster credentials
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # 6️⃣ Apply ConfigMap & Secret in Kubernetes
      - name: Apply Salesforce ConfigMap
        run: |
          kubectl apply -f kubernetes/base/configmap.yml
          kubectl apply -f kubernetes/base/secrets-salesforce.yml

      # 7️⃣ Deploy Salesforce Job to Kubernetes
      - name: Deploy Salesforce Job
        env:
          IMAGE_TAG: jayaprakashitc/salesforce-deployer:latest
        run: |
          echo "Deploying Salesforce Job..."
          # Replace only IMAGE_TAG in Job YAML
          envsubst '${IMAGE_TAG}' < kubernetes/base/job-deploy.yml | kubectl apply -f -

      # 8️⃣ Optional: Wait for Job completion
      - name: Wait for Salesforce Job to finish
        run: |
          JOB_NAME=$(kubectl get jobs -n default -o jsonpath='{.items[-1:].metadata.name}')
          echo "Waiting for job $JOB_NAME to complete..."
          kubectl wait --for=condition=complete --timeout=600s job/$JOB_NAME -n default
