name: Deploy Salesforce via GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # 2️⃣ Set up gcloud CLI and authenticate using Service Account
    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: grand-forge-472709-a0
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    # 3️⃣ Get GKE cluster credentials (kubectl context)
    - name: Authenticate GKE
      run: |
        gcloud container clusters get-credentials jpcluster \
          --zone us-central1-a \
          --project grand-forge-472709-a0

    # 4️⃣ Apply Kubernetes Secrets and ConfigMap (optional if already applied)
    - name: Apply Salesforce Secrets and ConfigMap
      run: |
        kubectl apply -f kubernetes/base/secret-salesforce.yaml -n default
        kubectl apply -f kubernetes/base/configmap.yaml -n default

    # 5️⃣ Apply Salesforce deployment Job
    - name: Deploy Salesforce Job
      run: |
        kubectl apply -f kubernetes/base/job-deploy.yaml -n default
        kubectl wait --for=condition=complete job/salesforce-deploy -n default --timeout=600s