name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker auth for GCR
        run: gcloud auth configure-docker --quiet

      # Build & push Docker image
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .\docker\Dockerfile
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/salesforce-deployer:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply Kubernetes Job
        run: |
          sed "s|\${IMAGE}|gcr.io/${{ secrets.GCP_PROJECT }}/salesforce-deployer:${{ github.sha }}|" k8s/job-deploy.yml | kubectl apply -f -
