name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # jayaprakashitc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & Push Docker image
      - name: Build & Push Salesforce Deployer Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jayaprakashitc/salesforce-deployer:latest

      # 4️⃣ Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 5️⃣ Get GKE cluster credentials
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # 6️⃣ Deploy Salesforce Job to Kubernetes
      - name: Deploy Salesforce Job
        env:
          IMAGE_TAG: jayaprakashitc/salesforce-deployer:latest
        run: |
          echo "Replacing image placeholder and deploying Job..."
          sed "s#\$***IMAGE***#${IMAGE_TAG}#g" kubernetes/base/job-deploy.yaml | kubectl create -f -
