name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # jayaprakashitc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jayaprakashitc/salesforce-deployer:latest

      # 4️⃣ Set Docker image variable
      - name: Set IMAGE variable
        run: echo "IMAGE_TAG=jayaprakashitc/salesforce-deployer:latest" >> $GITHUB_ENV
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
         cluster_name: jpcluster
         location: us-central1-a
         project_id: grand-forge-472709-a0
      - name: Deploy Salesforce Job to Kubernetes
        run: |
         sed "s|\${IMAGE}|${IMAGE_TAG}|" kubernetes/base/job-deploy.yaml | kubectl apply -f -
