name: Build & Deploy Salesforce

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # jayaprakashitc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Build & push Docker image
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jayaprakashitc/salesforce-deployer:latest

      # 4️⃣ Set Docker image variable
      - name: Set IMAGE variable
        run: echo "IMAGE_TAG=jayaprakashitc/salesforce-deployer:latest" >> $GITHUB_ENV

      # 5️⃣ Deploy to Kubernetes
      - name: Deploy Salesforce Job to Kubernetes
        run: |
          sed "s|\${IMAGE}|${IMAGE_TAG}|" kubernetes/base/job-deploy.yaml | kubectl apply -f -
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
